source :rubygems
ruby "1.8.7"
gem 'rails', '=2.3.18'
gem 'mime-types', '1.21'
gem 'pg'
gem 'authlogic', '>=0.1.0'
gem 'builder', '=2.1.2'
gem 'columnize'
gem 'crack'
gem 'curb'
gem 'database_cleaner'
gem 'diff-lcs'
gem 'haml'
gem 'json_pure', '>1.4.3'
gem 'linecache'
gem 'marc'
gem 'multipart-post'
gem 'nokogiri', '1.5.6'
gem 'rack'
gem 'rack-test'
gem 'httparty', '0.10.2'
#gem 'rake'
gem 'rake', '0.8.7' 
# gem 'rcov'
gem 'RedCloth'
gem 'rsolr', '=0.12.1'
gem 'rsolr-ext', '=0.12.0'
gem 'solr-ruby'
# gem 'sqlite3-ruby', '1.2.5'
gem 'term-ansicolor'
gem 'trollop'
gem 'webrat'
gem 'will_paginate', '=2.3.16'
gem 'xml-simple'
gem 'block_helpers'

