development:
  default:
    url: http://50.19.224.177:8080/solr 
  fulltext:
    url: http://50.19.224.177:8080/solr
test: &TEST
  default:
    url: http://localhost:8983/solr/development
  fulltext:
    url: http://localhost:8983/solr/development
production:
  default:
    url: http://50.19.224.177:8080/solr
  fulltext:
    url: http://50.19.224.177:8080/solr
cucumber:
  <<: *TEST
cucumber:
  <<: *TEST
